### ISSUE TITLE
Non consistent python minimal version

### ISSUE THREAD

**Issue by modir** [takeshixx/knxmap#22]
From main.py line 11ff:
```
# asyncio requires at least Python 3.3
if sys.version_info.major < 3 or \
        (sys.version_info.major > 2 and
         sys.version_info.minor < 3):
    print('At least Python version 3.3 is required to run this script!')
    sys.exit(1)
```

And from setup.py line 9 ff:
```
elif sys.version_info.major > 2 and \
                sys.version_info.minor < 4:
    print('Python 3.4 or newer is required')
    sys.exit(1)
```
It is just a small detail but it might be good to make it consistent. And maybe it is even better to have the check in only one of the two files. (Or create somewhere function for the check and then use everywhere this function.)

**Comment by takeshixx** [comment]
Fixed in 5f2725541d785e0b88c615bd639e391ae802d818. Python 3.3 is actually the real requirement, 3.4 only because it ships with asyncio by default. But the different checks didn't make a lot of sense.
