### ISSUE TITLE
knxmap can't detect remote gateway

### ISSUE THREAD

**Issue by marssys** [takeshixx/knxmap#6]
knxmap works well when I scan KNX gateway locally. But when I try to scan KNX gateway using remote IP address it can't detect gateway. Please see attached screenshot. First attempt - internal IP, second - external IP (of the same KNX gateway). ETS software can connect to remote IP address but I should use "using NAT" option (please see attached screenshot).

![1](https://cloud.githubusercontent.com/assets/17049612/23700002/73968f2c-0402-11e7-961f-84637bd583ed.png)

![ets](https://cloud.githubusercontent.com/assets/17049612/23700010/80ca2668-0402-11e7-9993-a5f6a1e01621.png)

**Comment by takeshixx** [comment]
Thanks for the hint. I've implemented the `--nat` switch (4048b68f661490959e548e57bab7ca079fe5a520) that is now available for description requests and tunnel connections which should allow to use the scanning mode in NAT scenarios. It has to be tested for all remaining modes (e.g. monitoring modes), especially if they work in NAT setups.
