### ISSUE TITLE
Scan - Tunnel connection timed out

### ISSUE THREAD

**Issue by GrayGhost93** [takeshixx/knxmap#8]
While I'm trying to scan a KNX-IP-Gateway (N000401) I get the error that the tunnel-connection timed out, while the monitoring (group-monitoring) seems to be the only thing that works fine... (Screenshot attached)
![timeout](https://user-images.githubusercontent.com/9499219/33878763-a52f60a8-df2c-11e7-9ba1-f96667976dfe.png)

**Comment by mar-schmidt** [comment]
I've got the same issue

**Comment by takeshixx** [comment]
Thanks for reporting this issue and sorry for the delayed response.
What versions of Python are your running on which operating system?

**Comment by GrayGhost93** [comment]
I'm using Python 3.6.3 on Windows 10.
But it works fine if I run the python file localy in the cloned folder without using the installed package...

**Comment by takeshixx** [comment]
That's strange. Are you sure that your installed version isn't outdated? You could try to install it into a local virtualenv in order to see if that has the same effect.

**Comment by mar-schmidt** [comment]
Im running python 3.5 on both my osx and rpi. Same issue on both ends

**Comment by mar-schmidt** [comment]
Cant seem to use the monitor function either as it gives me the followingerror

`root@raspberrypi:/home/pi/knxmap # /usr/local/opt/python-3.5.2/bin/knxmap -v monitor 192.168.1.63
[selector_events.py:65 -             __init__() ] Using selector: EpollSelector
[core.py:242 -              monitor() ] Starting bus monitor
[__init__.py:47 -        parse_message() ] Parsing KnxConnectResponse
[core.py:200 -     _unpack_knx_body() ] 37
Traceback (most recent call last):
  File "/usr/local/opt/python-3.5.2/lib/python3.5/site-packages/KNXmap-0.10.0-py3.5.egg/knxmap/messages/core.py", line 188, in _unpack_knx_body
    self.ERROR = KNX_STATUS_CODES[self.status]
KeyError: 37
`

**Comment by takeshixx** [comment]
This error is somehow different I guess as it references an error code that was not yet available in knxmap. In 400ccd529899fa1148eb8f609daa5b7fcf08e08f I've added the error code for your problem which is E_NO_MORE_UNIQUE_CONNECTIONS. I'm not sure what's the exact problem, but it could be device specific. It seems like there is no free channel available for a tunnel connection. Most devices have a very limited amount of available channels. Are you sure that you are not running multiple instances of knxmap or any other KNX tool (e.g. ETS)?

**Comment by takeshixx** [comment]
If the error still occurs, please reopen this issue.
