### ISSUE TITLE
Python 2 is not supported

### ISSUE THREAD

**Issue by ahmadnurhadirmw** [takeshixx/knxmap#9]
What happen ?
![cuplikan layar_2018-02-02_08-24-29](https://user-images.githubusercontent.com/26619526/35712008-896c4c98-07f2-11e8-898e-c6bf4977dda3.png)
My Python Versi 2.7 and 3.6

**Comment by 99anhadi** [comment]
Solve :+1:

**Comment by FalcoGer** [comment]
It states that it requires python 3.4 or higher.
Python 2 is the default for many linux distributions still for compatibility reasons. To explicitly call python 3 use the python3 command. try:
`python3 --version`
to run the setup script run
`sudo python setup.py install`
